services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:zHZxuLkoXFkMhGg/WSm8FnPdWsF+bE/iRWIeWFrASmU=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql103.infinityfree.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: if0_37906270_gespedido
      - key: DB_USERNAME
        value: if0_37906270
      - key: DB_PASSWORD
        value: L6YtTZpw3es0Q5v
